version: '3'
services:
 app:
  build: ./ghost
  volumes:
   - ./ghost/:/var/lib/ghost/content/
   - ./server:/var/lib/ghost/current/
  ports:
   - "127.0.0.1:8080:2368"
  environment:
   - NODE_ENV=development
